In [3]:
# Read Image
import cv2
# path 
path = r'D:\Profile\Photos\id.jpg'
# img = cv2.imread("1.jpg")
img = cv2.imread(path)  # create object for image
cv2.imshow("Output",img)
cv2.waitKey(0)

-1

In [3]:
# Show vido
import cv2
# path=  r'D:\Profile\Photos\11.mp4'

# videcap = cv2.VideoCapture(path)
videcap =cv2.VideoCapture("vid1.mp4")

while True:
    ret, frame = videcap.read()  # read frame by frame and ret is boolen
    # Read until video is completed
    if ret == True:     # We can remove it 
        cv2.imshow("Output Video",frame)
        # Press Q on keyboard to  exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    else:
        break 
        
       
   

In [1]:
# Live camera 
import cv2 
# If the input is taken from the camera, pass 0 instead of the video file name. 

vidlive = cv2.VideoCapture(0)

# We can set VideoCaptureProperties such as width and height and brightness 
#https://docs.opencv.org/3.4/d4/d15/group__videoio__flags__base.html#gaeb8dd9c89c10a5c63c139bf7c4f5704d
vidlive.set(3,640)
vidlive.set(4,400)
vidlive.set(10,90)

while True:
    ret, frame = vidlive.read() 
    if ret == True:     
        cv2.imshow("Output Video",frame)
        # Press Q on keyboard to  exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    else:
        break 

In [ ]:
vidlive.set(3,640)
vidlive.set(4,400)
vidlive.set(10,90)

In [1]:
# Basic image processing functions
import cv2
import numpy as np
img = cv2.imread("5.jpg")  # create object for image
print(img.shape)
#cv2.cvtColor() method
imGray =cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)  # Open CV is working with BGB 
# imLab =cv2.cvtColor(img,cv2.COLOR_BGR2Lab)
# imHSV =cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

# Gaussian  Blur
# imgGBlur = cv2.GaussianBlur(img,(3,3),0)
imgGBlur = cv2.GaussianBlur(imGray,(3,3),0)
# imgBlur2 = cv2.GaussianBlur(img,(21,21),0) more kernal size, more bluring 
imgEdgeCanny = cv2.Canny(img,120,100)  # we can decrease the edges by increase threshold
imgEdgeCanny2 = cv2.Canny(img,20,50)
# Dialation and Erode for image to make edge thicker or thinner
kernelmatrix = np.ones((5, 5), np.uint8)
imgDilate = cv2.dilate(imgEdgeCanny,kernelmatrix,1)
imgErode = cv2.erode(imgDilate,kernelmatrix,1)

cv2.imshow("Orginal",img)
cv2.imshow("Gray Image",imGray)
cv2.imshow("Blur Image",imgGBlur)
cv2.imshow("Canny Edge Image",imgEdgeCanny)
cv2.imshow("imgEdgeCanny2 Image",imgEdgeCanny2)
cv2.imshow("Dilated Image",imgDilate)
cv2.imshow("Eroded Image",imgErode)
cv2.waitKey(0)



(531, 413, 3)


-1

In [4]:
#Resizing and cropping image
import cv2
img = cv2.imread("1.jpg")  # create object for image
print(img.shape)  # height and width and channel

resizedimg = cv2.resize(img,(300,500)) # here width then height
print(resizedimg.shape)  # height and width and channel

croppedimg = img[100:300,200:550]

cv2.imshow("Orginal",img)
cv2.imshow("Resized Image",resizedimg)
cv2.imshow("Cropped Image",croppedimg)
cv2.waitKey(0)

(721, 900, 3)
(500, 300, 3)


-1

In [39]:
# Drawing shapes, lines with Color , then adding text
import cv2
import numpy as np

img = np.ones((600,600))  # white
img2 = np.zeros((600,600))  # black
imgcolor = np.zeros((600,600,3),np.uint8)

print(img.shape)
# imgcolor[:]=0,0,255 # BGR=00R(255 max)  whole image
imgcolor[200:500,300:400]=0,0,255 # BGR=00R(255 max) part of image



cv2.imshow("White",img)
cv2.imshow("Black",img2)
cv2.imshow("Colored Image",imgcolor)
cv2.waitKey(0)
# cv2.destroyAllWindows()
# imgcolor

(600, 600)


-1

In [19]:
# Drawing lines, rectangle with Color , then adding text
# https://www.cocyer.com/drawing-lines-on-images-using-cv2-line-in-python-opencv/#:~:text=Drawing%20Lines%20on%20Images%20Using%20cv2.line%20%28%29%20in,%280%2C0%29%2C%20%28width%2C%20height%29%2C%20%280%2C0%2C255%29%2C%2012%29%203%20Display%20image

import cv2
import numpy as np
imgcolor = np.zeros((600,600,3),np.uint8)
imgcolor2 = np.zeros((600,600,3),np.uint8)  # we can't use ones matrix here to make white background because it is color from 0 to 255
imgcolor2[:]=255,255,255     # so if we want to back white background we will make all BGR=255 255 255 
height = imgcolor.shape[0]
width = imgcolor.shape[1]
# Line cv2.line : starting point, ending point, color, width
cv2.line(imgcolor, (0,0),(300,450),(255,0,0),5)
cv2.line(imgcolor2,(0,0),(width,height),(255,255,0),5)

cv2.rectangle(imgcolor, (0,0),(300,450),(255,0,255),5)
cv2.rectangle(imgcolor, (320,400),(500,560),(255,0,255),-1)  # Thickness of -1 will fill the entire shape
cv2.circle(imgcolor,(420,200),30,(0,0,255),3)  # central point, radius
cv2.putText(imgcolor,"Hello opencv" ,(330,100),cv2.FONT_HERSHEY_COMPLEX,2,(0,255,255),3)  # text,location,font type,scale,color,thinkness

cv2.imshow("Drawing line",imgcolor )
cv2.imshow("Drawing line2",imgcolor2 )
cv2.waitKey(0)

-1

In [14]:
#  Warping Perspective and transformations
# https://www.pyimagesearch.com/2014/05/05/building-pokedex-python-opencv-perspective-warping-step-5-6/
import cv2
import numpy as np

img = cv2.imread("Cards2.jpg")

width,height = 180,250 # inital for new points(location)
points= np.float32([[250,129],[416,164],[197,368],[367,403]])
newpoints = np.float32([[0,0],[width,0],[0,height],[width,height]])
matrixTran = cv2.getPerspectiveTransform(points,newpoints) #transform
imgWrapOut = cv2.warpPerspective(img,matrixTran,(width,height))  #warp Perspective

cv2.imshow("Cards", img)
cv2.imshow("Out Card", imgWrapOut)
cv2.waitKey(0)

-1

### Stack and concatenate images

In [26]:
# Stack and concatenate images in one window  by using numpy h/vstack() or opencv h/vconcat ()
import cv2
import numpy as np

img = cv2.imread("Cards2.jpg")
# img2 = cv2.imread("5.jpg")
# They should have the same shape and number of cannels since they are matrics
Hstackedimg = np.hstack((img,img))  
Vstackedimg = np.vstack((img,img))

cv2.imshow("Horzontal Stack",Hstackedimg)
cv2.imshow("Vertical Stack",Vstackedimg)

cv2.waitKey(0)

# BUT thet face two issues, firstly the matrics should have the same shape and channels and also we can't chanhe in scale which is not optimim


-1

In [28]:
# hconcat(): It is used as cv2.hconcat() to concatenate images horizontally. Here h means horizontal.
# https://www.geeksforgeeks.org/concatenate-images-using-opencv-in-python/
import cv2
import numpy as np

img = cv2.imread("Cards2.jpg")
# img2 = cv2.imread("5.jpg")
# They should have the same shape and number of cannels since they are matrics
Hstackedimg = cv2.hconcat((img,img))  
Vstackedimg = cv2.vconcat((img,img))

cv2.imshow("Horzontal Stack",Hstackedimg)
cv2.imshow("Vertical Stack",Vstackedimg)

cv2.waitKey(0)

-1

In [11]:
# https://www.geeksforgeeks.org/concatenate-images-using-opencv-in-python/
# define a function for vertically 
# concatenating images of different
# widths 
import cv2
img = cv2.imread("Cards2.jpg")
img2 = cv2.imread("5.jpg")

def vconcat_resize(img_list, interpolation 
                   = cv2.INTER_CUBIC):
      # take minimum width
    w_min = min(img.shape[1] 
                for img in img_list)
      
    # resizing images
    im_list_resize = [cv2.resize(img,
                      (w_min, int(img.shape[0] * w_min / img.shape[1])),
                                 interpolation = interpolation)
                      for img in img_list]
    # return final image
    return cv2.vconcat(im_list_resize)

  
# function calling
img_v_resize = vconcat_resize([img, img2, img])

# Resize again the output ( we can do it inside the function or outside)
# img_h_resize2 = cv2.resize(img_h_resize, dsize = (900,900))
img_v_resize2 = cv2.resize(img_v_resize, dsize = (0,0),fx = 0.5, fy = 0.5) # This is better since we just rezise by scale

cv2.imshow("vconcat_resize.jpg",img_v_resize)
cv2.imshow("vconcat_resize2.jpg",img_v_resize2)

# cv2.imshow("Vertical Stack",Vstackedimg)
cv2.waitKey(0)
# show the output image
# cv2.imwrite('vconcat_resize.jpg', img_v_resize)

-1

In [10]:
# https://www.geeksforgeeks.org/concatenate-images-using-opencv-in-python/
# define a function for horizontally 
# concatenating images of different
# heights 
import cv2
img = cv2.imread("Cards2.jpg")
img2 = cv2.imread("5.jpg")

def hconcat_resize(img_list, 
                   interpolation 
                   = cv2.INTER_CUBIC):
      # take minimum hights
    h_min = min(img.shape[0] 
                for img in img_list)
      
    # image resizing 
    im_list_resize = [cv2.resize(img,
                       (int(img.shape[1] * h_min / img.shape[0]),
                        h_min), interpolation
                                 = interpolation) 
                      for img in img_list]
      
    # return final image
    return cv2.hconcat(im_list_resize)
  
# function calling
img_h_resize = hconcat_resize([img, img2, img])

# Resize again the output
# img_h_resize2 = cv2.resize(img_h_resize, dsize = (900,900))
img_h_resize2 = cv2.resize(img_h_resize, dsize = (0,0),fx = 0.5, fy = 0.5) # This is better since we just rezise by scale

# show the Output image

cv2.imshow('hconcat_resize.jpg', img_h_resize)
cv2.imshow('hconcat_resize2.jpg', img_h_resize2)

cv2.waitKey(0)


-1

In [15]:
# concatenating vertically images of the same size  and horizontally
import cv2
img = cv2.imread("2.jpg")

def concat_vh(list_2d):
    
      # return final image
    return cv2.vconcat([cv2.hconcat(list_h) 
                        for list_h in list_2d])
# image resizing
img1_s = cv2.resize(img, dsize = (0,0),
                    fx = 0.2, fy = 0.2)
  
# function calling
img_tile = concat_vh([[img1_s, img1_s, img1_s],
                      [img1_s, img1_s, img1_s],
                      [img1_s, img1_s, img1_s]])
# show the output image
cv2.imshow('concat_vh.jpg', img_tile)
cv2.waitKey(0)


-1

In [26]:
# define a function for concatenating images of different sizes in vertical and horizontal tiles

import cv2
img1 = cv2.imread("4.jpg")
img2 = cv2.imread("5.jpg")
img3 = cv2.imread("3.jpg")
img4= cv2.cvtColor(img2,cv2.COLOR_BGRA2GRAY)

def concat_tile_resize(list_2d, 
                       interpolation = cv2.INTER_CUBIC):
      # function calling for every 
    # list of images
    img_list_v = [hconcat_resize(list_h, 
                                 interpolation = cv2.INTER_CUBIC) 
                  for list_h in list_2d]
      
    # return final image
    return vconcat_resize(img_list_v, interpolation=cv2.INTER_CUBIC)



# function calling
im_tile_resize = concat_tile_resize([[img1],
                                     [img1, img2,
                                      img1, img3, img1],
                                     [img1, img2, img3]])


# REsize again
im_tile_resize2 = cv2.resize(im_tile_resize, dsize = (0,0),
                    fx = 0.5, fy = 0.5)
# show the image
cv2.imshow('concat_tile_resize.jpg', im_tile_resize2)
# cv2.imshow('grey.jpg', img4) 
cv2.waitKey(0)

# Still we face issue if we need to concate two images with different channels

-1

In [5]:
# Here the another function  to stack between two images with different channels
# https://github.com/murtazahassan/Learn-OpenCV-in-3-hours/blob/master/chapter6.py
import cv2
import numpy as np


def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

img = cv2.imread('1.jpg')
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

imgStack = stackImages(0.3,([img,imgGray,img],[img,img,img]))

# imgHor = np.hstack((img,img))
# imgVer = np.vstack((img,img))
#
# cv2.imshow("Horizontal",imgHor)
# cv2.imshow("Vertical",imgVer)
cv2.imshow("ImageStack",imgStack)

cv2.waitKey(0)

-1

###  bitwise

In [1]:
import cv2 as cv
import numpy as np

blank = np.zeros((400,400), dtype='uint8')

rectangle = cv.rectangle(blank.copy(), (30,30), (370,370), 255, -1)
circle = cv.circle(blank.copy(), (200,200), 200, 255, -1)

cv.imshow('Rectangle', rectangle)
cv.imshow('Circle', circle)

# bitwise AND --> intersecting regions
bitwise_and = cv.bitwise_and(rectangle, circle)
cv.imshow('Bitwise AND', bitwise_and)

# bitwise OR --> non-intersecting and intersecting regions
bitwise_or = cv.bitwise_or(rectangle, circle)
cv.imshow('Bitwise OR', bitwise_or)

# bitwise XOR --> non-intersecting regions
bitwise_xor = cv.bitwise_xor(rectangle, circle)
cv.imshow('Bitwise XOR', bitwise_xor)

# bitwise NOT
bitwise_not = cv.bitwise_not(circle)
cv.imshow('Circle NOT', bitwise_not)

cv.waitKey(0)

-1

### Mask

In [3]:
import cv2 as cv
import numpy as np

img = cv.imread('2.jpg')
cv.imshow('Cats', img)

blank = np.zeros(img.shape[:2], dtype='uint8')  # :2 to be same shape (two dimensions)
cv.imshow('Blank Image', blank)
cv.waitKey(0)
print(img.shape, blank.shape)

(1200, 1600, 3) (1200, 1600)


In [1]:
import cv2 as cv
import numpy as np

img = cv.imread('birds.jpg')
cv.imshow('Cats', img)

blank = np.zeros(img.shape[:2], dtype='uint8')
cv.imshow('Blank Image', blank)

circle = cv.circle(blank.copy(), (img.shape[1]//2 + 45,img.shape[0]//2), 200, 255, -1)

rectangle = cv.rectangle(blank.copy(), (30,30), (370,370), 255, -1)

cv.imshow('C', circle)
cv.imshow('R', rectangle)
maskc= cv.bitwise_and(img,img,mask=circle)
cv.imshow('MC', maskc)

# weird_shape = cv.bitwise_and(circle,rectangle)
# cv.imshow('Weird Shape', weird_shape)

# masked = cv.bitwise_and(img,img,mask=weird_shape)
# cv.imshow('Weird Shaped Masked Image', masked)

cv.waitKey(0)

-1

In [2]:
import cv2 as cv
import numpy as np

img = cv.imread('birds.jpg')
cv.imshow('Cats', img)

blank = np.zeros(img.shape[:2], dtype='uint8')
cv.imshow('Blank Image', blank)

circle = cv.circle(blank.copy(), (img.shape[1]//2 + 45,img.shape[0]//2), 200, 255, -1)

rectangle = cv.rectangle(blank.copy(), (30,30), (370,370), 255, -1)

weird_shape = cv.bitwise_and(circle,rectangle)
cv.imshow('Weird Shape', weird_shape)

masked = cv.bitwise_and(img,img,mask=weird_shape)
cv.imshow('Weird Shaped Masked Image', masked)

cv.waitKey(0)

-1

### Thresholding

In [1]:
import cv2 as cv

img = cv.imread('birds.jpg')
cv.imshow('Cats', img)

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('Gray', gray)

# Simple Thresholding
threshold, thresh = cv.threshold(gray, 150, 255, cv.THRESH_BINARY )
cv.imshow('Simple Thresholded', thresh)

threshold, thresh_inv = cv.threshold(gray, 150, 255, cv.THRESH_BINARY_INV )
cv.imshow('Simple Thresholded Inverse', thresh_inv)

# Adaptive Thresholding (Make computer find the best threshold for me)
adaptive_thresh = cv.adaptiveThreshold(gray, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY_INV, 11, 9)
cv.imshow('Adaptive Thresholding', adaptive_thresh)

cv.waitKey(0)
print(threshold, thresh)

150.0 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Edge Detection and gradients

In [2]:
# there are different topics however in OpenCV there are common functions that can be used for them 
import cv2 as cv
import numpy as np

img = cv.imread('nile.jpg')
cv.imshow('Orginal', img)

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('Gray', gray)

# Laplacian
lap = cv.Laplacian(gray, cv.CV_64F)
lap = np.uint8(np.absolute(lap))
cv.imshow('Laplacian', lap)

# Sobel 
sobelx = cv.Sobel(gray, cv.CV_64F, 1, 0)
sobely = cv.Sobel(gray, cv.CV_64F, 0, 1)
combined_sobel = cv.bitwise_or(sobelx, sobely)

cv.imshow('Sobel X', sobelx)
cv.imshow('Sobel Y', sobely)
cv.imshow('Combined Sobel', combined_sobel)

canny = cv.Canny(gray, 150, 175)
cv.imshow('Canny', canny)
cv.waitKey(0)

-1